[default]
extend-ignore-re = [
  "Selector:0.*Signature:.*", # polycli abi
  "cosmos1[a-z0-9]{38}",      # bech32 addresses in heimdall docs/tests
  "BA\\{[0-9]+:",             # CometBFT BitArray notation, e.g. BA{2:x_}
]

[default.extend-identifiers]
GetProcotolName = "GetProcotolName" # typo in PolygonDataCommittee contract

[default.extend-words]
AIMD = "AIMD" # accronym for Additive Increase Multiplicative Decrease
BLOK = "BLOK" # accronym for block
THR = "THR"   # accronym for throughput

[files]
extend-exclude = [
  "go.mod",
  "go.sum",
  "bindings/",
  "contracts/lib",
  "hdwallet/hdwallet_test.go",
  "cmd/dockerlogger/dockerlogger.go",
]
