// Code generated by "stringer -type=loadTestMode"; DO NOT EDIT.

package loadtest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[loadTestModeERC20-0]
	_ = x[loadTestModeERC721-1]
	_ = x[loadTestModeBlob-2]
	_ = x[loadTestModeContractCall-3]
	_ = x[loadTestModeDeploy-4]
	_ = x[loadTestModeIncrement-5]
	_ = x[loadTestModeRandom-6]
	_ = x[loadTestModeRecall-7]
	_ = x[loadTestModeRPC-8]
	_ = x[loadTestModeStore-9]
	_ = x[loadTestModeTransaction-10]
	_ = x[loadTestModeUniswapV3-11]
}

const _loadTestMode_name = "loadTestModeERC20loadTestModeERC721loadTestModeBlobloadTestModeContractCallloadTestModeDeployloadTestModeIncrementloadTestModeRandomloadTestModeRecallloadTestModeRPCloadTestModeStoreloadTestModeTransactionloadTestModeUniswapV3"

var _loadTestMode_index = [...]uint8{0, 17, 35, 51, 75, 93, 114, 132, 150, 165, 182, 205, 226}

func (i loadTestMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_loadTestMode_index)-1 {
		return "loadTestMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _loadTestMode_name[_loadTestMode_index[idx]:_loadTestMode_index[idx+1]]
}
