FROM --platform=$BUILDPLATFORM golang:1.23-bookworm

WORKDIR /gen

RUN apt-get update

## Install nodejs and npm
RUN apt-get install -y nodejs npm

## Install jq
RUN apt-get install -y jq

CMD ./scripts/rpctypes.sh rpctypes/jsonschemas/
