[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@openzeppelin/=lib/openzeppelin-contracts/contracts',
]

# Lite profile with Yul optimizer disabled.
[profile.lite.optimizer_details]
yul = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
