[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@openzeppelin/=lib/openzeppelin-contracts/contracts',
]
solc_version = "0.8.23" # https://github.com/ethereum/solidity/releases

# default profile with Yul optimiser disabled.
[profile.default.optimizer_details]
yul = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
