// Code generated by "stringer -type=Mode"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeERC20-0]
	_ = x[ModeERC721-1]
	_ = x[ModeBlob-2]
	_ = x[ModeContractCall-3]
	_ = x[ModeDeploy-4]
	_ = x[ModeIncrement-5]
	_ = x[ModeRandom-6]
	_ = x[ModeRecall-7]
	_ = x[ModeRPC-8]
	_ = x[ModeStore-9]
	_ = x[ModeTransaction-10]
	_ = x[ModeUniswapV3-11]
}

const _Mode_name = "ModeERC20ModeERC721ModeBlobModeContractCallModeDeployModeIncrementModeRandomModeRecallModeRPCModeStoreModeTransactionModeUniswapV3"

var _Mode_index = [...]uint8{0, 9, 19, 27, 43, 53, 66, 76, 86, 93, 102, 117, 130}

func (i Mode) String() string {
	if i < 0 || i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
