name: ci

on: push

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: "1.21"
  # Check https://grpc.io/docs/languages/go/quickstart/ for `protoc` versions.
  PROTOC_VERSION: "24.3"
  PROTOC_GEN_GO_VERSION: "1.28"
  PROTOC_GEN_GO_GRPC_VERSION: "1.2"
  ARCH: "linux-x86_64"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: (github.event.action != 'closed' || github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - name: Install shadow
        run: go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
      - name: Run all the linter tools against code
        run: make lint

  gen:
    name: Check generated files
    runs-on: ubuntu-latest
    if: (github.event.action != 'closed' || github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      # make gen-proto
      - name: Install protoc
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_VERSION }}/protoc-${{ env.PROTOC_VERSION }}-${{ env.ARCH }}.zip
          unzip protoc-${{ env.PROTOC_VERSION }}-${{ env.ARCH }}.zip
          sudo mv bin/protoc /usr/local/bin/
          sudo mv include/google /usr/local/include
          protoc --version
      - name: Install protoc plugins for go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v${{ env.PROTOC_GEN_GO_VERSION }}
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v${{ env.PROTOC_GEN_GO_GRPC_VERSION }}
          protoc-gen-go --version
          protoc-gen-go-grpc --version

      # make gen-go-bindings
      - name: Install abigen
        run: |
          sudo add-apt-repository ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install ethereum
          abigen --version
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install dependencies
        working-directory: contracts
        run: forge install

      - name: Try to generate new files
        run: make gen
      - name: Check if files are up to date
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "❌ Error: File are not up to date. Please run \`make gen\`."
            git diff
            exit 1
          else
            echo "✅ Files are up to date."
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    if: (github.event.action != 'closed' || github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run tests
        run: make test

  loadtest:
    name: Loadtest against geth
    runs-on: ubuntu-latest
    if: (github.event.action != 'closed' || github.event.pull_request.merged == true)
    strategy:
      matrix:
        tool: [geth, anvil]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        # foundry only has nightly versions no we don't specify a version at the moment.
      - name: Install Geth
        run: |
          if [ "${{ matrix.tool }}" = "geth" ]; then
            sudo add-apt-repository ppa:ethereum/ethereum
            sudo apt-get update
            sudo apt-get install ethereum
            geth --version
          fi
      - name: Run loadtest againt ${{ matrix.tool }}
        run: |
          ${{ matrix.tool }} --version
          make ${{ matrix.tool }} &
          sleep 5
          make loadtest
